services:
  svelte:
    build: .
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true